
# sudo docker compose --file=./docker-compose.yml up --force-recreate --build

version: '3.8'
services:
  auth:
    build:
      context: ../ # path of parent directory
      dockerfile: ./auth/Dockerfile # path relative to context
    restart: "no"
    ports:
      - 9090:9090
    command: node ./index.mjs