# 
# sudo docker compose build --no-cache
# sudo docker compose create --force-recreate
# sudo docker compose up
# 
# sudo docker compose up --build --force-recreate
# 
# sudo docker compose down
# sudo docker compose rm

version: '3.8'
services:
  postgresql:
    image: postgres:14
    restart: "no"
    network_mode: "host" # 5432
    command: "postgres"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${POSTGRES_USER:?error}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?error}
    volumes:
     - ./volumes/postgresql/data:/var/lib/postgresql/data
  postgrest:
    image: postgrest/postgrest
    network_mode: "host" # 5433
    environment:
      PGRST_DB_ANON_ROLE: anon
      PGRST_DB_SCHEMAS: ${PGRST_DB_SCHEMAS:?error}
      PGRST_DB_EXTRA_SEARCH_PATH: ${PGRST_DB_EXTRA_SEARCH_PATH:?error}
      PGRST_DB_URI: postgres://authenticator:${POSTGRES_PASSWORD:?error}@0.0.0.0:5432/postgres
      PGRST_SERVER_PORT: 5433
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET:?error}
      PGRST_JWT_SECRET_IS_BASE64: ${PGRST_JWT_SECRET_IS_BASE64:?error}
      PGRST_JWT_AUD: crestfall
    depends_on:
      - postgresql